### PR TITLE
Include badge with version and website in crate list

### PR DESCRIPTION
**Pull request by mgrojo**

### CODE REVIEW

**Comment by mgrojo** [comment]
The badge gives uniformity to the presentation of crates, and version and website will give more information to this too bare list.

**Comment by Fabien-Chouteau** [comment]
Hi @mgrojo, thanks for the contributions.

I add two screenshots blow to show in the PR what the result looks like.

For me this change is bringing a lot of visual confusion for information that is only one click away. Especially when viewed on smaller screens. I prefer to keep the current style that is compact and more readable in my opinion.

Screenshot 2023-09-18 120214
Screenshot 2023-09-18 120236

**Comment by mgrojo** [comment]
Ok. That's naturally arguable, but this is your development, so I humbly understand. However, just to justify my proposal, look at how opam or cargo present crate lists:

https://opam.ocaml.org/packages/index-date.html
https://crates.io/crates?sort=new

They probably have better designers than me or you, but the amount of information is greater or similar.

**Comment by Fabien-Chouteau** [comment]
> https://opam.ocaml.org/packages/index-date.html 
The Opam list is very similar to what we have for Alire, the only differences being that the latest version is displayed and a table kind of style. It's not clear to me what is the added value of showing the last version number in this list...

However they have a view sorted by "last update date" which is cool. I am not sure we are able to do that at the moment...

> https://crates.io/crates?sort=new

Cargo is a different beast in terms of scale, they cannot display a list of all crates in one page (125749 vs sub 400 for Alire).
So I can see why you would make a different choice in that case. Some of the information provided on the Cargo crate list are not available for Alire, such as the number of downloads or the time since the last update.

**Comment by mgrojo** [comment]
> However they have a view sorted by "last update date" which is cool. I am not sure we are able to do that at the moment...

Why not? Is the index not always obtained via git clone? In case it is, it's just a matter of executing:
```shell
git log --pretty="format:%ci" crate-release.toml
```
Even if not always obtained via git, it would make sense to get the value when it is, and set to an unknown value, when it is not (or get it from the file timestamp if that makes sense in that fetch method).

**Comment by Fabien-Chouteau** [comment]
> Why not? Is the index not always obtained via git clone? In case it is, it's just a matter of executing:

It has to be part of the `alr show --jekyll` output though. I don't want to have something just for the website.

**Comment by mgrojo** [comment]
> > Why not? Is the index not always obtained via git clone? In case it is, it's just a matter of executing:
> 
> It has to be part of the `alr show --jekyll` output though. I don't want to have something just for the website.

Yes, of course, I didn't suggest doing it from the website generation, but with a change in the information provided by `alr`. Maybe I understood your comment as referring to Alire and you meant only alire.ada.dev.

**Pull request closed without merging**
