### PR TITLE
Crate page revamp and front page fix

### PR DESCRIPTION
**Pull request by Fabien-Chouteau**

### CODE REVIEW

**Comment by Fabien-Chouteau** [comment]
2023-03-22-183146_1920x1080_scrot

**Comment by jquorning** [comment]
Looking good :-)
I haven't checked on my machine thougt. My MacBook is for some uncertain reason out of businness (#apple,#shouldhaveusedada) at this time.
My brand new refurbed Windows 10 is not yet fully functional for Ada development (#powershell,#howto).

**Review by mosteo — APPROVED** [review]

**Comment by mosteo** [comment]
Looks great. My only suggestion is that maybe the badge in the sidebar should be nearer the top, instead of below a variable number of dependencies/dependents.

**Comment by Fabien-Chouteau** [comment]
> My only suggestion is that maybe the badge in the sidebar should be nearer the top, instead of below a variable number of dependencies/dependents.

That's what I did first, but the reason why we have the badge on this page is for the maintainers to have an easy way to get the link (e.g. https://img.shields.io/endpoint?url=https://alire.ada.dev/badges/ado.json). It doesn't bring much value to most readers of the page.

**Pull request merged**
